name: annie-gtk builder (CI)
on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - name: Setup GTK environment
        run: |
          sudo apt-get update
          sudo apt install -y git meson build-essential libgtk-3-dev gettext
      - name: Build annie-gtk
        run: |
          go mod tidy
          go build -o build/annie-gtk
      - name: Upload annie-gtk
        uses: actions/upload-artifact@v2
        with:
         path: build/annie-gtk
