name: annie-gtk builder for windows (CI)
on:
  push:
    branches:
      - master
      - github-actions
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: 135e2/mingw-gtk-docker:master
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Show files
        run: | 
          ls -a /mingw64
          ls -a ../
      - name: Build annie-gtk
        run: |
          sed -i -e 's/-Wl,-luuid/-luuid/g' /mingw64/lib/pkgconfig/gdk-3.0.pc
          CGO_ENABLED=1 CC=x86_64-w64-mingw32-cc GOOS=windows GOARCH=amd64 \
          go install github.com/gotk3/gotk3/gtk
          go mod tidy
          CGO_ENABLED=1 CC=x86_64-w64-mingw32-cc GOOS=windows GOARCH=amd64 \
          go build -ldflags -H=windowsgui -o build/annie-gtk.exe
      - name: Copy files to build path
        run: |
          echo "Searching DLL"
          FILE=$(ls build/*.exe | xargs basename)
          mingw-ldd build/$FILE --dll-lookup-dirs /mingw64/bin | grep -o '/mingw64/bin.*$' | xargs cp -t build
          echo "End searching dll"
          echo "Copying UI file..."
          cp -v annie-gtk.ui build/annie-gtk.ui
      - name: Upload annie-gtk
        uses: actions/upload-artifact@v2
        with:
          path: build/
          name: annie-gtk_windows